services:
  network-deploy-service:
    networks:
      - tynysai

  microservice-db-config:
    extends:
      service: network-deploy-service
    image: postgres:17
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}

  microservice-configserver-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      JAVA_TOOL_OPTIONS: "-javaagent:/app/libs/opentelemetry-javaagent-2.23.0.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none

  microservice-eurekaserver-config:
    extends:
      service: microservice-configserver-config
    depends_on:
      config-server:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8071/

  microservice-base-config:
    extends:
      service: microservice-eurekaserver-config
    depends_on:
      eureka-server:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_DB_PASSWORD}
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: "kafka:9092"
      TZ: "Asia/Almaty"
      KEYCLOAK_ISSUER_URI: "http://localhost:7080/realms/tynysai"
      KEYCLOAK_JWK_SET_URI: "http://keycloak:8080/realms/tynysai/protocol/openid-connect/certs"