services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.1
    container_name: keycloak
    ports:
      - "127.0.0.1:7080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
    command: "start-dev"
    extends:
      file: common-config.yml
      service: network-deploy-service

  read:
    image: grafana/loki:latest
    container_name: read
    command: "-config.file=/etc/loki/config.yaml -target=read"
    ports:
      - 3101:3100
      - 7946
      - 9095
    volumes:
      - ../observability/loki/loki-config.yaml:/etc/loki/config.yaml
    depends_on:
      - minio
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: &loki-dns
      tynysai:
        aliases:
          - loki

  write:
    image: grafana/loki:latest
    container_name: write
    command: "-config.file=/etc/loki/config.yaml -target=write"
    ports:
      - 3102:3100
      - 7946
      - 9095
    volumes:
      - ../observability/loki/loki-config.yaml:/etc/loki/config.yaml
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - minio
    networks:
      <<: *loki-dns

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    volumes:
      - ../observability/alloy/alloy-local-config.yaml:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    ports:
      - 12345:12345
    depends_on:
      - gateway
    extends:
      file: common-config.yml
      service: network-deploy-service

  minio:
    image: minio/minio
    container_name: minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        minio server /data
    environment:
      - MINIO_ROOT_USER=loki
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    ports:
      - 9000
    volumes:
      - ./.data/minio:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 15s
      timeout: 20s
      retries: 5
    extends:
      file: common-config.yml
      service: network-deploy-service

  prometheus:
    image: prom/prometheus:v3.8.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ../observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    extends:
      file: common-config.yml
      service: network-deploy-service

  tempo:
    image: grafana/tempo:2.9.0
    container_name: tempo
    command:
      - -config.file=/etc/tempo-config.yml
    ports:
      - "3110:3100"
      - "4318:4318"
    volumes:
      - ../observability/tempo/tempo.yml:/etc/tempo-config.yml
    extends:
      file: common-config.yml
      service: network-deploy-service

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - gateway
    entrypoint:
      - sh
      - -euc
      - |
        /run.sh
    ports:
      - "3000:3000"
    volumes:
      - ../observability/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    extends:
      file: common-config.yml
      service: network-deploy-service

  backend:
    image: grafana/loki:latest
    container_name: backend
    volumes:
      - ../observability/loki/loki-config.yaml:/etc/loki/config.yaml
    ports:
      - "3100"
      - "7946"
    command: "-config.file=/etc/loki/config.yaml -target=backend -legacy-read-mode=false"
    depends_on:
      - gateway
    extends:
      file: common-config.yml
      service: network-deploy-service

  gateway:
    image: nginx:latest
    container_name: gateway
    depends_on:
      - read
      - write
    entrypoint:
      - sh
      - -euc
      - |
        cat <<EOF > /etc/nginx/nginx.conf
        user  nginx;
        worker_processes  5;  ## Default: 1

        events {
          worker_connections   1000;
        }

        http {
          resolver 127.0.0.11;

          server {
            listen             3100;

            location = / {
              return 200 'OK';
              auth_basic off;
            }

            location = /api/prom/push {
              proxy_pass       http://write:3100\$$request_uri;
            }

            location = /api/prom/tail {
              proxy_pass       http://read:3100\$$request_uri;
              proxy_set_header Upgrade \$$http_upgrade;
              proxy_set_header Connection "upgrade";
            }

            location ~ /api/prom/.* {
              proxy_pass       http://read:3100\$$request_uri;
            }

            location = /loki/api/v1/push {
              proxy_pass       http://write:3100\$$request_uri;
            }

            location = /loki/api/v1/tail {
              proxy_pass       http://read:3100\$$request_uri;
              proxy_set_header Upgrade \$$http_upgrade;
              proxy_set_header Connection "upgrade";
            }

            location ~ /loki/api/.* {
              proxy_pass       http://read:3100\$$request_uri;
            }
          }
        }
        EOF
        /docker-entrypoint.sh nginx -g "daemon off;"
    ports:
      - "3100:3100"
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    extends:
      file: common-config.yml
      service: network-deploy-service

  users-db:
    container_name: users-db
    environment:
      POSTGRES_DB: tynysai_users
    extends:
      file: common-config.yml
      service: microservice-db-config

  appointments-db:
    container_name: appointments-db
    environment:
      POSTGRES_DB: tynysai_appointments
    extends:
      file: common-config.yml
      service: microservice-db-config

  medical-records-db:
    container_name: medical-records-db
    environment:
      POSTGRES_DB: tynysai_medical_records
    extends:
      file: common-config.yml
      service: microservice-db-config

  notifications-db:
    container_name: notifications-db
    environment:
      POSTGRES_DB: tynysai_notifications
    extends:
      file: common-config.yml
      service: microservice-db-config

  xrays-db:
    container_name: xrays-db
    environment:
      POSTGRES_DB: tynysai_xrays
    extends:
      file: common-config.yml
      service: microservice-db-config

  ai-service:
    build:
      context: ../../xray-service/ai_service
    image: "bekasyl04/ai-service-tynysai:1.0.0"
    container_name: ai-service-ms
    ports:
      - "8000:8000"
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail --silent http://localhost:8000/health || exit 1" ]
      interval: 20s
      timeout: 5s
      retries: 10
      start_period: 30s
    extends:
      file: common-config.yml
      service: network-deploy-service

  kafka:
    image: apache/kafka:4.1.1
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    healthcheck:
      test: [ "CMD-SHELL", "nc -z kafka 9092 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-deploy-service

  config-server:
    image: "bekasyl04/config-server-tynysai:1.0.0"
    container_name: config-server-ms
    ports:
      - "8071:8071"
    environment:
      SPRING_APPLICATION_NAME: "config-server"
      OTEL_SERVICE_NAME: "config-server"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep 'UP' || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  eureka-server:
    image: "bekasyl04/eureka-server-tynysai:1.0.0"
    container_name: eureka-server-ms
    ports:
      - "8070:8070"
    environment:
      SPRING_APPLICATION_NAME: "eureka-server"
      OTEL_SERVICE_NAME: "eureka-server"
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep 'UP' || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-eurekaserver-config

  user-service:
    image: "bekasyl04/user-service-tynysai:1.0.0"
    container_name: user-service-ms
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep 'UP' || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://users-db:5432/tynysai_users"
      SPRING_APPLICATION_NAME: "user-service"
      OTEL_SERVICE_NAME: "user-service"
      KEYCLOAK_SERVER-URL: "http://keycloak:8080"
      KEYCLOAK_ADMIN_SECRET: ${KEYCLOAK_ADMIN_SECRET}
    depends_on:
      users-db:
        condition: service_healthy
      keycloak:
        condition: service_started
      kafka:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config

  medical-record-service:
    image: "bekasyl04/medical-record-service-tynysai:1.0.0"
    container_name: medical-record-service-ms
    healthcheck:
      test: "curl --fail --silent localhost:8090/actuator/health/readiness | grep 'UP' || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://medical-records-db:5432/tynysai_medical_records"
      SPRING_APPLICATION_NAME: "medical-record-service"
      OTEL_SERVICE_NAME: "medical-record-service"
    depends_on:
      medical-records-db:
        condition: service_healthy
      keycloak:
        condition: service_started
      kafka:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config

  appointment-service:
    image: "bekasyl04/appointment-service-tynysai:1.0.0"
    container_name: appointment-service-ms
    healthcheck:
      test: "curl --fail --silent localhost:9000/actuator/health/readiness | grep 'UP' || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://appointments-db:5432/tynysai_appointments"
      SPRING_APPLICATION_NAME: "appointment-service"
      OTEL_SERVICE_NAME: "appointment-service"
    depends_on:
      appointments-db:
        condition: service_healthy
      keycloak:
        condition: service_started
      kafka:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config

  notification-service:
    image: "bekasyl04/notification-service-tynysai:1.0.0"
    container_name: notification-service-ms
    healthcheck:
      test: "curl --fail --silent localhost:9010/actuator/health/readiness | grep 'UP' || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://notifications-db:5432/tynysai_notifications"
      SPRING_APPLICATION_NAME: "notification-service"
      OTEL_SERVICE_NAME: "notification-service"
    depends_on:
      notifications-db:
        condition: service_healthy
      keycloak:
        condition: service_started
      kafka:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config

  xray-service:
    image: "bekasyl04/xray-service-tynysai:1.0.0"
    container_name: xray-service-ms
    healthcheck:
      test: "curl --fail --silent localhost:9020/actuator/health/readiness | grep 'UP' || exit 1"
      interval: 20s
      timeout: 5s
      retries: 20
      start_period: 10s
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://xrays-db:5432/tynysai_xrays"
      SPRING_APPLICATION_NAME: "xray-service"
      OTEL_SERVICE_NAME: "xray-service"
      APP_AI_SERVICE-URL: "http://ai-service:8000"
    depends_on:
      xrays-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      ai-service:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-base-config

  gateway-server:
    image: "bekasyl04/gateway-server-tynysai:1.0.0"
    container_name: gateway-server-ms
    ports:
      - "8072:8072"
    environment:
      SPRING_APPLICATION_NAME: "gateway-server"
      OTEL_SERVICE_NAME: "gateway-server"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8080/realms/tynysai/protocol/openid-connect/certs"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI: "http://keycloak:8080/realms/tynysai"
    depends_on:
      user-service:
        condition: service_healthy
      medical-record-service:
        condition: service_healthy
      appointment-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
      xray-service:
        condition: service_healthy
      kafka:
        condition: service_healthy
      keycloak:
        condition: service_started
    extends:
      file: common-config.yml
      service: microservice-base-config

networks:
  tynysai:
    driver: "bridge"