CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id UUID NOT NULL,
    doctor_id UUID NOT NULL,
    status VARCHAR(20) NOT NULL,
    appointment_date TIMESTAMP,
    patient_complaints TEXT,
    doctor_notes TEXT,
    report_id BIGINT,
    xray_analysis_id BIGINT,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_appointment_patient ON appointments (patient_id);
CREATE INDEX IF NOT EXISTS idx_appointment_doctor ON appointments (doctor_id);